[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
googletest = "0.10.0"

[[bin]]
name = "day2_exec"
test = true
bench = true
path = "src/day2_main.rs"
